### PR TITLE
Do not clear the post cache if the current_url_supercache_dir matches…

### PR DESCRIPTION
**Pull request by kraftbj**
… the supercache_dir. 
See #45

### CODE REVIEW

**Comment by Sophist-UK** [comment]
For clarity, @graphicsxp was referring to #98 which he reported.

@graphicsxp - I think that this does fix the problem of all cache being deleted, but does NOT fix the problem of list pages (like blog pages showing all or specific categories of posts) needing to be invalidated. However this is a new problem which needs investigating.

**Comment by graphicsxp** [comment]
ok then :) So it is not normal behaviour ?

**Comment by Sophist-UK** [comment]
Actually,now I have reviewed the code again, I am not sure that this is the fix that is needed.

Function prune_super_cache is the routine which prunes the cache and it recursively prunes all subdirectories. This works for simple blogs where the category list has the posts in subdirectories, but is overkill for hierarchical pages (i.e. deletes too many pages), and can easily be incomplete i.e. it doesn't do archives, it doesn't do pages which e.g. use the list-category-posts plugin etc.

I think we should move this discussion to #98.

**Comment by donnchawp** [comment]
A similar check was added in #420. Closing this.

**Pull request closed without merging**
