### PR TITLE
Rename this back as it's needed for WordPress.org

### PR DESCRIPTION
**Pull request by donnchawp**
File was renamed in #452 but plugins on WordPress.org need a readme.txt

### CODE REVIEW

**Comment by timse201** [comment]
.txt isnt needed at wp.org. There are many Plugins using md files. Its not really nice but it has styling compatibility for both

**Comment by donnchawp** [comment]
@timse201 are you sure? I looked at the plugins I have installed and a number of them have a readme.md but they also have a readme.txt

**Comment by stodorovic** [comment]
@timse201 readme.txt is needed because it contains: `Tested up to:`, `Stable tag:`, `Requires at least:`. ... Please look https://wordpress.org/plugins/wp-super-cache/ and you will see them on right sidebar.

More info on https://codex.wordpress.org/Writing_a_Plugin:
> # Readme File
> If you want to host your Plugin on https://wordpress.org/plugins/, you need to create a readme.txt file within your plugin directory in a standardized format. You can use the automatic plugin 'readme.txt' generator.

**Comment by timse201** [comment]
https://plugins.trac.wordpress.org/browser/cachify/#tags/2.2.4

**Comment by stodorovic** [comment]
If we are going into this direction, you can see https://github.com/Yoast/wordpress-seo There are both readme.txt and readme.MD

I'm not sure that you way is good. I'd like to we follow codex.wordpress.org. Maybe, I'm wrong, but can you find some documentation about it?

Also, @timse201 Please look #459 Did you test all your PRs? I saw few errors in your code.

**Comment by timse201** [comment]
cant find official documentation but ! i found some tickets

https://meta.trac.wordpress.org/ticket/403

**Comment by stodorovic** [comment]
There are a couple contradictions. First [ticket 403](https://meta.trac.wordpress.org/ticket/403) is reported by Joost de Valk (the founder of Yoast), but Yoast SEO has both (separate) files on github and only readme.txt on wordpress.org (which uses old format).

Also, [ticket 403](https://meta.trac.wordpress.org/ticket/403) recommends `readme.txt`:

> There are no plans to support GitHub flavored markdown. For this reason, we continue to recommend using the name "readme.txt" and not "readme.md", as they are unlikely to be of the same format. Additionally, GitHub uses the readme.md for entirely different purposes than the plugin directory does.

**Comment by timse201** [comment]
sure because there were some issues left.
but these are fixed as i know.
you can upload md file with the new version and check it and if it is not working you can rename it in seconds ;)

**Pull request merged**
