### PR TITLE
add wpsc_enable_wp_config_edit filter

### PR DESCRIPTION
**Pull request by mathieuhays**
Implements a solution for #372

### CODE REVIEW

**Comment by donnchawp** [comment]
I made a small change to your patch that added a debug log to the deactivate function. Unfortunately the wp_cache_debug() function isn't available when the plugin is activated so I had to remove it from that after I added it there too..

Can you make one more change to the wp_cache_create_advanced_cache() function? Don't put the check for `$should_update_wp_config` in the file permissions if() - use a new one and print an error message appropriate for it, and return false.

**Comment by mathieuhays** [comment]
Sure, will do

**Comment by mathieuhays** [comment]
I'm not sure what's your process to generate the .po files. 

In case you want the fr_FR translation for the new error message:
`Not allowed to edit %s per configuration.`
`Changement de %s interdit par la configuration.`

**Comment by donnchawp** [comment]
Thanks @mathieuhays - I've merged it as it's so small. 

Translations can be done through the [Translating WordPress site](https://translate.wordpress.org/projects/wp-plugins/wp-super-cache). :)

**Pull request merged**
